export enum TipoNotificacao{
  EDITORPLATAFORMA = 0,
  DEIXOUDESEREDITOR,
  CONVITENOVOGRUPO,
  ACEITOUSERADICIONADONOGRUPO,
  RECUSOUSERADICIONADONOGRUPO,
  EDITORGRUPO,
  OWNERGRUPO,
  PARTICIPANTEGRUPO
}
